# Generated by Django 4.2.10 on 2025-12-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'Kakao'), (3, 'Naver'), (4, 'Google')], default=1),
        ),
    ]
