# Generated by Django 4.2.10 on 2025-12-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tokenapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_status',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
