# Generated by Django 4.2.10 on 2025-12-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_service_key_user_token_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
