# Generated by Django 4.2.10 on 2025-12-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_withdrawn_user_withdrawn_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remaining_requests',
            field=models.IntegerField(default=10),
        ),
    ]
