# Generated by Django 4.2.10 on 2025-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_username_and_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paramedicinfo',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
