# Generated by Django 4.2.10 on 2025-11-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_role_alter_paramedicinfo_affiliation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
