# Generated by Django 4.2.10 on 2025-12-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_license_verified_user_license_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamedicAuthHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_option', models.CharField(max_length=10)),
                ('jumin', models.CharField(max_length=50)),
                ('dsnm', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=20)),
                ('telecom_gubun', models.CharField(blank=True, max_length=10, null=True)),
                ('result', models.BooleanField(default=False)),
                ('response_msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ParamedicInfo',
        ),
    ]
