# Generated by Django 4.2.10 on 2025-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_latitude_user_location_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='radius',
            field=models.IntegerField(default=10),
        ),
    ]
