# Generated by Django 4.2.10 on 2025-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationlog',
            name='radius',
            field=models.IntegerField(default=10),
        ),
    ]
