# Generated by Django 4.2.10 on 2025-12-19 04:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_symptomsearchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='symptomsearchlog',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomsearchlog',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
