# Generated by Django 4.2.10 on 2025-12-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_location_symptomsearchlog_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsearchlog',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
