# Generated by Django 4.2.10 on 2025-12-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_symptomsearchlog_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsearchlog',
            name='ai_recommended_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomsearchlog',
            name='openai_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
