# Generated by Django 4.2.10 on 2025-12-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_symptomsearchlog_ai_recommended_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
