# Generated by Django 4.2.10 on 2025-12-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_bookmark_bookmark_unique_user_hospital_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalrealtimestatus',
            name='hvcc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalrealtimestatus',
            name='hvccc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalrealtimestatus',
            name='hvicc',
            field=models.IntegerField(default=0),
        ),
    ]
