# Generated by Django 4.2.10 on 2025-12-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_hospitalrealtimestatus_hvcc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsearchlog',
            name='sign_kind',
            field=models.IntegerField(default=1),
        ),
    ]
