# Generated by Django 4.2.10 on 2025-12-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_symptomsearchlog_sign_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='ai_model_used',
            field=models.CharField(blank=True, default='NONE', max_length=50, null=True),
        ),
    ]
